//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace DocumentManager.Web.Model
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class documentmanagerEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new documentmanagerEntities object using the connection string found in the 'documentmanagerEntities' section of the application configuration file.
        /// </summary>
        public documentmanagerEntities() : base("name=documentmanagerEntities", "documentmanagerEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new documentmanagerEntities object.
        /// </summary>
        public documentmanagerEntities(string connectionString) : base(connectionString, "documentmanagerEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new documentmanagerEntities object.
        /// </summary>
        public documentmanagerEntities(EntityConnection connection) : base(connection, "documentmanagerEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<action> action
        {
            get
            {
                if ((_action == null))
                {
                    _action = base.CreateObjectSet<action>("action");
                }
                return _action;
            }
        }
        private ObjectSet<action> _action;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<filetype> filetype
        {
            get
            {
                if ((_filetype == null))
                {
                    _filetype = base.CreateObjectSet<filetype>("filetype");
                }
                return _filetype;
            }
        }
        private ObjectSet<filetype> _filetype;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<systemlog> systemlog
        {
            get
            {
                if ((_systemlog == null))
                {
                    _systemlog = base.CreateObjectSet<systemlog>("systemlog");
                }
                return _systemlog;
            }
        }
        private ObjectSet<systemlog> _systemlog;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<taxpayer> taxpayer
        {
            get
            {
                if ((_taxpayer == null))
                {
                    _taxpayer = base.CreateObjectSet<taxpayer>("taxpayer");
                }
                return _taxpayer;
            }
        }
        private ObjectSet<taxpayer> _taxpayer;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<taxpayerdocument> taxpayerdocument
        {
            get
            {
                if ((_taxpayerdocument == null))
                {
                    _taxpayerdocument = base.CreateObjectSet<taxpayerdocument>("taxpayerdocument");
                }
                return _taxpayerdocument;
            }
        }
        private ObjectSet<taxpayerdocument> _taxpayerdocument;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<taxpayertype> taxpayertype
        {
            get
            {
                if ((_taxpayertype == null))
                {
                    _taxpayertype = base.CreateObjectSet<taxpayertype>("taxpayertype");
                }
                return _taxpayertype;
            }
        }
        private ObjectSet<taxpayertype> _taxpayertype;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<user> user
        {
            get
            {
                if ((_user == null))
                {
                    _user = base.CreateObjectSet<user>("user");
                }
                return _user;
            }
        }
        private ObjectSet<user> _user;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<useraction> useraction
        {
            get
            {
                if ((_useraction == null))
                {
                    _useraction = base.CreateObjectSet<useraction>("useraction");
                }
                return _useraction;
            }
        }
        private ObjectSet<useraction> _useraction;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<standbook> standbook
        {
            get
            {
                if ((_standbook == null))
                {
                    _standbook = base.CreateObjectSet<standbook>("standbook");
                }
                return _standbook;
            }
        }
        private ObjectSet<standbook> _standbook;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the action EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToaction(action action)
        {
            base.AddObject("action", action);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the filetype EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTofiletype(filetype filetype)
        {
            base.AddObject("filetype", filetype);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the systemlog EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosystemlog(systemlog systemlog)
        {
            base.AddObject("systemlog", systemlog);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the taxpayer EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotaxpayer(taxpayer taxpayer)
        {
            base.AddObject("taxpayer", taxpayer);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the taxpayerdocument EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotaxpayerdocument(taxpayerdocument taxpayerdocument)
        {
            base.AddObject("taxpayerdocument", taxpayerdocument);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the taxpayertype EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotaxpayertype(taxpayertype taxpayertype)
        {
            base.AddObject("taxpayertype", taxpayertype);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the user EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTouser(user user)
        {
            base.AddObject("user", user);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the useraction EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTouseraction(useraction useraction)
        {
            base.AddObject("useraction", useraction);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the standbook EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTostandbook(standbook standbook)
        {
            base.AddObject("standbook", standbook);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="documentmanagerModel", Name="action")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class action : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new action object.
        /// </summary>
        /// <param name="action_id">Initial value of the action_id property.</param>
        public static action Createaction(global::System.Int32 action_id)
        {
            action action = new action();
            action.action_id = action_id;
            return action;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 action_id
        {
            get
            {
                return _action_id;
            }
            set
            {
                if (_action_id != value)
                {
                    Onaction_idChanging(value);
                    ReportPropertyChanging("action_id");
                    _action_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("action_id");
                    Onaction_idChanged();
                }
            }
        }
        private global::System.Int32 _action_id;
        partial void Onaction_idChanging(global::System.Int32 value);
        partial void Onaction_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String action_name
        {
            get
            {
                return _action_name;
            }
            set
            {
                Onaction_nameChanging(value);
                ReportPropertyChanging("action_name");
                _action_name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("action_name");
                Onaction_nameChanged();
            }
        }
        private global::System.String _action_name;
        partial void Onaction_nameChanging(global::System.String value);
        partial void Onaction_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> supper_action_id
        {
            get
            {
                return _supper_action_id;
            }
            set
            {
                Onsupper_action_idChanging(value);
                ReportPropertyChanging("supper_action_id");
                _supper_action_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("supper_action_id");
                Onsupper_action_idChanged();
            }
        }
        private Nullable<global::System.Int32> _supper_action_id;
        partial void Onsupper_action_idChanging(Nullable<global::System.Int32> value);
        partial void Onsupper_action_idChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="documentmanagerModel", Name="filetype")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class filetype : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new filetype object.
        /// </summary>
        /// <param name="file_type_id">Initial value of the file_type_id property.</param>
        public static filetype Createfiletype(global::System.Int32 file_type_id)
        {
            filetype filetype = new filetype();
            filetype.file_type_id = file_type_id;
            return filetype;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 file_type_id
        {
            get
            {
                return _file_type_id;
            }
            set
            {
                if (_file_type_id != value)
                {
                    Onfile_type_idChanging(value);
                    ReportPropertyChanging("file_type_id");
                    _file_type_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("file_type_id");
                    Onfile_type_idChanged();
                }
            }
        }
        private global::System.Int32 _file_type_id;
        partial void Onfile_type_idChanging(global::System.Int32 value);
        partial void Onfile_type_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String file_type_name
        {
            get
            {
                return _file_type_name;
            }
            set
            {
                Onfile_type_nameChanging(value);
                ReportPropertyChanging("file_type_name");
                _file_type_name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("file_type_name");
                Onfile_type_nameChanged();
            }
        }
        private global::System.String _file_type_name;
        partial void Onfile_type_nameChanging(global::System.String value);
        partial void Onfile_type_nameChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="documentmanagerModel", Name="standbook")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class standbook : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new standbook object.
        /// </summary>
        /// <param name="standbook_id">Initial value of the standbook_id property.</param>
        public static standbook Createstandbook(global::System.String standbook_id)
        {
            standbook standbook = new standbook();
            standbook.standbook_id = standbook_id;
            return standbook;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String standbook_id
        {
            get
            {
                return _standbook_id;
            }
            set
            {
                if (_standbook_id != value)
                {
                    Onstandbook_idChanging(value);
                    ReportPropertyChanging("standbook_id");
                    _standbook_id = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("standbook_id");
                    Onstandbook_idChanged();
                }
            }
        }
        private global::System.String _standbook_id;
        partial void Onstandbook_idChanging(global::System.String value);
        partial void Onstandbook_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String projectname
        {
            get
            {
                return _projectname;
            }
            set
            {
                OnprojectnameChanging(value);
                ReportPropertyChanging("projectname");
                _projectname = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("projectname");
                OnprojectnameChanged();
            }
        }
        private global::System.String _projectname;
        partial void OnprojectnameChanging(global::System.String value);
        partial void OnprojectnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> totalmoney
        {
            get
            {
                return _totalmoney;
            }
            set
            {
                OntotalmoneyChanging(value);
                ReportPropertyChanging("totalmoney");
                _totalmoney = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("totalmoney");
                OntotalmoneyChanged();
            }
        }
        private Nullable<global::System.Decimal> _totalmoney;
        partial void OntotalmoneyChanging(Nullable<global::System.Decimal> value);
        partial void OntotalmoneyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String taxpayername
        {
            get
            {
                return _taxpayername;
            }
            set
            {
                OntaxpayernameChanging(value);
                ReportPropertyChanging("taxpayername");
                _taxpayername = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("taxpayername");
                OntaxpayernameChanged();
            }
        }
        private global::System.String _taxpayername;
        partial void OntaxpayernameChanging(global::System.String value);
        partial void OntaxpayernameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String taxpayerpersonname
        {
            get
            {
                return _taxpayerpersonname;
            }
            set
            {
                OntaxpayerpersonnameChanging(value);
                ReportPropertyChanging("taxpayerpersonname");
                _taxpayerpersonname = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("taxpayerpersonname");
                OntaxpayerpersonnameChanged();
            }
        }
        private global::System.String _taxpayerpersonname;
        partial void OntaxpayerpersonnameChanging(global::System.String value);
        partial void OntaxpayerpersonnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String capitalcontruction
        {
            get
            {
                return _capitalcontruction;
            }
            set
            {
                OncapitalcontructionChanging(value);
                ReportPropertyChanging("capitalcontruction");
                _capitalcontruction = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("capitalcontruction");
                OncapitalcontructionChanged();
            }
        }
        private global::System.String _capitalcontruction;
        partial void OncapitalcontructionChanging(global::System.String value);
        partial void OncapitalcontructionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> hasoutverify
        {
            get
            {
                return _hasoutverify;
            }
            set
            {
                OnhasoutverifyChanging(value);
                ReportPropertyChanging("hasoutverify");
                _hasoutverify = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("hasoutverify");
                OnhasoutverifyChanged();
            }
        }
        private Nullable<global::System.Boolean> _hasoutverify;
        partial void OnhasoutverifyChanging(Nullable<global::System.Boolean> value);
        partial void OnhasoutverifyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> paytime
        {
            get
            {
                return _paytime;
            }
            set
            {
                OnpaytimeChanging(value);
                ReportPropertyChanging("paytime");
                _paytime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("paytime");
                OnpaytimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _paytime;
        partial void OnpaytimeChanging(Nullable<global::System.DateTime> value);
        partial void OnpaytimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> thispartmoney
        {
            get
            {
                return _thispartmoney;
            }
            set
            {
                OnthispartmoneyChanging(value);
                ReportPropertyChanging("thispartmoney");
                _thispartmoney = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("thispartmoney");
                OnthispartmoneyChanged();
            }
        }
        private Nullable<global::System.Decimal> _thispartmoney;
        partial void OnthispartmoneyChanging(Nullable<global::System.Decimal> value);
        partial void OnthispartmoneyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> hasaddedvaluetax
        {
            get
            {
                return _hasaddedvaluetax;
            }
            set
            {
                OnhasaddedvaluetaxChanging(value);
                ReportPropertyChanging("hasaddedvaluetax");
                _hasaddedvaluetax = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("hasaddedvaluetax");
                OnhasaddedvaluetaxChanged();
            }
        }
        private Nullable<global::System.Boolean> _hasaddedvaluetax;
        partial void OnhasaddedvaluetaxChanging(Nullable<global::System.Boolean> value);
        partial void OnhasaddedvaluetaxChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> addedvaluetax
        {
            get
            {
                return _addedvaluetax;
            }
            set
            {
                OnaddedvaluetaxChanging(value);
                ReportPropertyChanging("addedvaluetax");
                _addedvaluetax = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("addedvaluetax");
                OnaddedvaluetaxChanged();
            }
        }
        private Nullable<global::System.Decimal> _addedvaluetax;
        partial void OnaddedvaluetaxChanging(Nullable<global::System.Decimal> value);
        partial void OnaddedvaluetaxChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String addedvaluetaxitem
        {
            get
            {
                return _addedvaluetaxitem;
            }
            set
            {
                OnaddedvaluetaxitemChanging(value);
                ReportPropertyChanging("addedvaluetaxitem");
                _addedvaluetaxitem = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("addedvaluetaxitem");
                OnaddedvaluetaxitemChanged();
            }
        }
        private global::System.String _addedvaluetaxitem;
        partial void OnaddedvaluetaxitemChanging(global::System.String value);
        partial void OnaddedvaluetaxitemChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> addedvaluetaxrate
        {
            get
            {
                return _addedvaluetaxrate;
            }
            set
            {
                OnaddedvaluetaxrateChanging(value);
                ReportPropertyChanging("addedvaluetaxrate");
                _addedvaluetaxrate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("addedvaluetaxrate");
                OnaddedvaluetaxrateChanged();
            }
        }
        private Nullable<global::System.Decimal> _addedvaluetaxrate;
        partial void OnaddedvaluetaxrateChanging(Nullable<global::System.Decimal> value);
        partial void OnaddedvaluetaxrateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> hasbusinesstax
        {
            get
            {
                return _hasbusinesstax;
            }
            set
            {
                OnhasbusinesstaxChanging(value);
                ReportPropertyChanging("hasbusinesstax");
                _hasbusinesstax = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("hasbusinesstax");
                OnhasbusinesstaxChanged();
            }
        }
        private Nullable<global::System.Boolean> _hasbusinesstax;
        partial void OnhasbusinesstaxChanging(Nullable<global::System.Boolean> value);
        partial void OnhasbusinesstaxChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> businesstax
        {
            get
            {
                return _businesstax;
            }
            set
            {
                OnbusinesstaxChanging(value);
                ReportPropertyChanging("businesstax");
                _businesstax = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("businesstax");
                OnbusinesstaxChanged();
            }
        }
        private Nullable<global::System.Decimal> _businesstax;
        partial void OnbusinesstaxChanging(Nullable<global::System.Decimal> value);
        partial void OnbusinesstaxChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String businesstaxitem
        {
            get
            {
                return _businesstaxitem;
            }
            set
            {
                OnbusinesstaxitemChanging(value);
                ReportPropertyChanging("businesstaxitem");
                _businesstaxitem = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("businesstaxitem");
                OnbusinesstaxitemChanged();
            }
        }
        private global::System.String _businesstaxitem;
        partial void OnbusinesstaxitemChanging(global::System.String value);
        partial void OnbusinesstaxitemChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> businestaxrate
        {
            get
            {
                return _businestaxrate;
            }
            set
            {
                OnbusinestaxrateChanging(value);
                ReportPropertyChanging("businestaxrate");
                _businestaxrate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("businestaxrate");
                OnbusinestaxrateChanged();
            }
        }
        private Nullable<global::System.Decimal> _businestaxrate;
        partial void OnbusinestaxrateChanging(Nullable<global::System.Decimal> value);
        partial void OnbusinestaxrateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> haseducationsurtax
        {
            get
            {
                return _haseducationsurtax;
            }
            set
            {
                OnhaseducationsurtaxChanging(value);
                ReportPropertyChanging("haseducationsurtax");
                _haseducationsurtax = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("haseducationsurtax");
                OnhaseducationsurtaxChanged();
            }
        }
        private Nullable<global::System.Boolean> _haseducationsurtax;
        partial void OnhaseducationsurtaxChanging(Nullable<global::System.Boolean> value);
        partial void OnhaseducationsurtaxChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> educationsurtax
        {
            get
            {
                return _educationsurtax;
            }
            set
            {
                OneducationsurtaxChanging(value);
                ReportPropertyChanging("educationsurtax");
                _educationsurtax = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("educationsurtax");
                OneducationsurtaxChanged();
            }
        }
        private Nullable<global::System.Decimal> _educationsurtax;
        partial void OneducationsurtaxChanging(Nullable<global::System.Decimal> value);
        partial void OneducationsurtaxChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String educationsurtaxitem
        {
            get
            {
                return _educationsurtaxitem;
            }
            set
            {
                OneducationsurtaxitemChanging(value);
                ReportPropertyChanging("educationsurtaxitem");
                _educationsurtaxitem = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("educationsurtaxitem");
                OneducationsurtaxitemChanged();
            }
        }
        private global::System.String _educationsurtaxitem;
        partial void OneducationsurtaxitemChanging(global::System.String value);
        partial void OneducationsurtaxitemChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> educationsurtaxrate
        {
            get
            {
                return _educationsurtaxrate;
            }
            set
            {
                OneducationsurtaxrateChanging(value);
                ReportPropertyChanging("educationsurtaxrate");
                _educationsurtaxrate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("educationsurtaxrate");
                OneducationsurtaxrateChanged();
            }
        }
        private Nullable<global::System.Decimal> _educationsurtaxrate;
        partial void OneducationsurtaxrateChanging(Nullable<global::System.Decimal> value);
        partial void OneducationsurtaxrateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> hasurbantax
        {
            get
            {
                return _hasurbantax;
            }
            set
            {
                OnhasurbantaxChanging(value);
                ReportPropertyChanging("hasurbantax");
                _hasurbantax = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("hasurbantax");
                OnhasurbantaxChanged();
            }
        }
        private Nullable<global::System.Boolean> _hasurbantax;
        partial void OnhasurbantaxChanging(Nullable<global::System.Boolean> value);
        partial void OnhasurbantaxChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> urbantax
        {
            get
            {
                return _urbantax;
            }
            set
            {
                OnurbantaxChanging(value);
                ReportPropertyChanging("urbantax");
                _urbantax = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("urbantax");
                OnurbantaxChanged();
            }
        }
        private Nullable<global::System.Decimal> _urbantax;
        partial void OnurbantaxChanging(Nullable<global::System.Decimal> value);
        partial void OnurbantaxChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String urbantaxitem
        {
            get
            {
                return _urbantaxitem;
            }
            set
            {
                OnurbantaxitemChanging(value);
                ReportPropertyChanging("urbantaxitem");
                _urbantaxitem = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("urbantaxitem");
                OnurbantaxitemChanged();
            }
        }
        private global::System.String _urbantaxitem;
        partial void OnurbantaxitemChanging(global::System.String value);
        partial void OnurbantaxitemChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> urbantaxrate
        {
            get
            {
                return _urbantaxrate;
            }
            set
            {
                OnurbantaxrateChanging(value);
                ReportPropertyChanging("urbantaxrate");
                _urbantaxrate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("urbantaxrate");
                OnurbantaxrateChanged();
            }
        }
        private Nullable<global::System.Decimal> _urbantaxrate;
        partial void OnurbantaxrateChanging(Nullable<global::System.Decimal> value);
        partial void OnurbantaxrateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> haslocaleducationsurtax
        {
            get
            {
                return _haslocaleducationsurtax;
            }
            set
            {
                OnhaslocaleducationsurtaxChanging(value);
                ReportPropertyChanging("haslocaleducationsurtax");
                _haslocaleducationsurtax = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("haslocaleducationsurtax");
                OnhaslocaleducationsurtaxChanged();
            }
        }
        private Nullable<global::System.Boolean> _haslocaleducationsurtax;
        partial void OnhaslocaleducationsurtaxChanging(Nullable<global::System.Boolean> value);
        partial void OnhaslocaleducationsurtaxChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> localeducationsurtax
        {
            get
            {
                return _localeducationsurtax;
            }
            set
            {
                OnlocaleducationsurtaxChanging(value);
                ReportPropertyChanging("localeducationsurtax");
                _localeducationsurtax = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("localeducationsurtax");
                OnlocaleducationsurtaxChanged();
            }
        }
        private Nullable<global::System.Decimal> _localeducationsurtax;
        partial void OnlocaleducationsurtaxChanging(Nullable<global::System.Decimal> value);
        partial void OnlocaleducationsurtaxChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String localeducationsurtaxitem
        {
            get
            {
                return _localeducationsurtaxitem;
            }
            set
            {
                OnlocaleducationsurtaxitemChanging(value);
                ReportPropertyChanging("localeducationsurtaxitem");
                _localeducationsurtaxitem = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("localeducationsurtaxitem");
                OnlocaleducationsurtaxitemChanged();
            }
        }
        private global::System.String _localeducationsurtaxitem;
        partial void OnlocaleducationsurtaxitemChanging(global::System.String value);
        partial void OnlocaleducationsurtaxitemChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> localeducationsurtaxrate
        {
            get
            {
                return _localeducationsurtaxrate;
            }
            set
            {
                OnlocaleducationsurtaxrateChanging(value);
                ReportPropertyChanging("localeducationsurtaxrate");
                _localeducationsurtaxrate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("localeducationsurtaxrate");
                OnlocaleducationsurtaxrateChanged();
            }
        }
        private Nullable<global::System.Decimal> _localeducationsurtaxrate;
        partial void OnlocaleducationsurtaxrateChanging(Nullable<global::System.Decimal> value);
        partial void OnlocaleducationsurtaxrateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> hasstamptax
        {
            get
            {
                return _hasstamptax;
            }
            set
            {
                OnhasstamptaxChanging(value);
                ReportPropertyChanging("hasstamptax");
                _hasstamptax = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("hasstamptax");
                OnhasstamptaxChanged();
            }
        }
        private Nullable<global::System.Boolean> _hasstamptax;
        partial void OnhasstamptaxChanging(Nullable<global::System.Boolean> value);
        partial void OnhasstamptaxChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> stamptax
        {
            get
            {
                return _stamptax;
            }
            set
            {
                OnstamptaxChanging(value);
                ReportPropertyChanging("stamptax");
                _stamptax = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("stamptax");
                OnstamptaxChanged();
            }
        }
        private Nullable<global::System.Decimal> _stamptax;
        partial void OnstamptaxChanging(Nullable<global::System.Decimal> value);
        partial void OnstamptaxChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String stamptaxitem
        {
            get
            {
                return _stamptaxitem;
            }
            set
            {
                OnstamptaxitemChanging(value);
                ReportPropertyChanging("stamptaxitem");
                _stamptaxitem = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("stamptaxitem");
                OnstamptaxitemChanged();
            }
        }
        private global::System.String _stamptaxitem;
        partial void OnstamptaxitemChanging(global::System.String value);
        partial void OnstamptaxitemChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> stamptaxrate
        {
            get
            {
                return _stamptaxrate;
            }
            set
            {
                OnstamptaxrateChanging(value);
                ReportPropertyChanging("stamptaxrate");
                _stamptaxrate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("stamptaxrate");
                OnstamptaxrateChanged();
            }
        }
        private Nullable<global::System.Decimal> _stamptaxrate;
        partial void OnstamptaxrateChanging(Nullable<global::System.Decimal> value);
        partial void OnstamptaxrateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> hasincometax
        {
            get
            {
                return _hasincometax;
            }
            set
            {
                OnhasincometaxChanging(value);
                ReportPropertyChanging("hasincometax");
                _hasincometax = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("hasincometax");
                OnhasincometaxChanged();
            }
        }
        private Nullable<global::System.Boolean> _hasincometax;
        partial void OnhasincometaxChanging(Nullable<global::System.Boolean> value);
        partial void OnhasincometaxChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> incometax
        {
            get
            {
                return _incometax;
            }
            set
            {
                OnincometaxChanging(value);
                ReportPropertyChanging("incometax");
                _incometax = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("incometax");
                OnincometaxChanged();
            }
        }
        private Nullable<global::System.Decimal> _incometax;
        partial void OnincometaxChanging(Nullable<global::System.Decimal> value);
        partial void OnincometaxChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String incometaxitem
        {
            get
            {
                return _incometaxitem;
            }
            set
            {
                OnincometaxitemChanging(value);
                ReportPropertyChanging("incometaxitem");
                _incometaxitem = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("incometaxitem");
                OnincometaxitemChanged();
            }
        }
        private global::System.String _incometaxitem;
        partial void OnincometaxitemChanging(global::System.String value);
        partial void OnincometaxitemChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> incometaxrate
        {
            get
            {
                return _incometaxrate;
            }
            set
            {
                OnincometaxrateChanging(value);
                ReportPropertyChanging("incometaxrate");
                _incometaxrate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("incometaxrate");
                OnincometaxrateChanged();
            }
        }
        private Nullable<global::System.Decimal> _incometaxrate;
        partial void OnincometaxrateChanging(Nullable<global::System.Decimal> value);
        partial void OnincometaxrateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String invoicenumber
        {
            get
            {
                return _invoicenumber;
            }
            set
            {
                OninvoicenumberChanging(value);
                ReportPropertyChanging("invoicenumber");
                _invoicenumber = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("invoicenumber");
                OninvoicenumberChanged();
            }
        }
        private global::System.String _invoicenumber;
        partial void OninvoicenumberChanging(global::System.String value);
        partial void OninvoicenumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String taxreceiptnumber
        {
            get
            {
                return _taxreceiptnumber;
            }
            set
            {
                OntaxreceiptnumberChanging(value);
                ReportPropertyChanging("taxreceiptnumber");
                _taxreceiptnumber = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("taxreceiptnumber");
                OntaxreceiptnumberChanged();
            }
        }
        private global::System.String _taxreceiptnumber;
        partial void OntaxreceiptnumberChanging(global::System.String value);
        partial void OntaxreceiptnumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> groupid
        {
            get
            {
                return _groupid;
            }
            set
            {
                OngroupidChanging(value);
                ReportPropertyChanging("groupid");
                _groupid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("groupid");
                OngroupidChanged();
            }
        }
        private Nullable<global::System.Int32> _groupid;
        partial void OngroupidChanging(Nullable<global::System.Int32> value);
        partial void OngroupidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String economicnature
        {
            get
            {
                return _economicnature;
            }
            set
            {
                OneconomicnatureChanging(value);
                ReportPropertyChanging("economicnature");
                _economicnature = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("economicnature");
                OneconomicnatureChanged();
            }
        }
        private global::System.String _economicnature;
        partial void OneconomicnatureChanging(global::System.String value);
        partial void OneconomicnatureChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String phonenumber
        {
            get
            {
                return _phonenumber;
            }
            set
            {
                OnphonenumberChanging(value);
                ReportPropertyChanging("phonenumber");
                _phonenumber = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("phonenumber");
                OnphonenumberChanged();
            }
        }
        private global::System.String _phonenumber;
        partial void OnphonenumberChanging(global::System.String value);
        partial void OnphonenumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> totaltaxrate
        {
            get
            {
                return _totaltaxrate;
            }
            set
            {
                OntotaltaxrateChanging(value);
                ReportPropertyChanging("totaltaxrate");
                _totaltaxrate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("totaltaxrate");
                OntotaltaxrateChanged();
            }
        }
        private Nullable<global::System.Decimal> _totaltaxrate;
        partial void OntotaltaxrateChanging(Nullable<global::System.Decimal> value);
        partial void OntotaltaxrateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String note
        {
            get
            {
                return _note;
            }
            set
            {
                OnnoteChanging(value);
                ReportPropertyChanging("note");
                _note = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("note");
                OnnoteChanged();
            }
        }
        private global::System.String _note;
        partial void OnnoteChanging(global::System.String value);
        partial void OnnoteChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="documentmanagerModel", Name="systemlog")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class systemlog : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new systemlog object.
        /// </summary>
        /// <param name="system_log_id">Initial value of the system_log_id property.</param>
        public static systemlog Createsystemlog(global::System.Int32 system_log_id)
        {
            systemlog systemlog = new systemlog();
            systemlog.system_log_id = system_log_id;
            return systemlog;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 system_log_id
        {
            get
            {
                return _system_log_id;
            }
            set
            {
                if (_system_log_id != value)
                {
                    Onsystem_log_idChanging(value);
                    ReportPropertyChanging("system_log_id");
                    _system_log_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("system_log_id");
                    Onsystem_log_idChanged();
                }
            }
        }
        private global::System.Int32 _system_log_id;
        partial void Onsystem_log_idChanging(global::System.Int32 value);
        partial void Onsystem_log_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String system_log
        {
            get
            {
                return _system_log;
            }
            set
            {
                Onsystem_logChanging(value);
                ReportPropertyChanging("system_log");
                _system_log = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("system_log");
                Onsystem_logChanged();
            }
        }
        private global::System.String _system_log;
        partial void Onsystem_logChanging(global::System.String value);
        partial void Onsystem_logChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="documentmanagerModel", Name="taxpayer")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class taxpayer : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new taxpayer object.
        /// </summary>
        /// <param name="taxpayer_id">Initial value of the taxpayer_id property.</param>
        public static taxpayer Createtaxpayer(global::System.Int32 taxpayer_id)
        {
            taxpayer taxpayer = new taxpayer();
            taxpayer.taxpayer_id = taxpayer_id;
            return taxpayer;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 taxpayer_id
        {
            get
            {
                return _taxpayer_id;
            }
            set
            {
                if (_taxpayer_id != value)
                {
                    Ontaxpayer_idChanging(value);
                    ReportPropertyChanging("taxpayer_id");
                    _taxpayer_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("taxpayer_id");
                    Ontaxpayer_idChanged();
                }
            }
        }
        private global::System.Int32 _taxpayer_id;
        partial void Ontaxpayer_idChanging(global::System.Int32 value);
        partial void Ontaxpayer_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String taxpayer_code
        {
            get
            {
                return _taxpayer_code;
            }
            set
            {
                Ontaxpayer_codeChanging(value);
                ReportPropertyChanging("taxpayer_code");
                _taxpayer_code = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("taxpayer_code");
                Ontaxpayer_codeChanged();
            }
        }
        private global::System.String _taxpayer_code;
        partial void Ontaxpayer_codeChanging(global::System.String value);
        partial void Ontaxpayer_codeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String taxpayer_name
        {
            get
            {
                return _taxpayer_name;
            }
            set
            {
                Ontaxpayer_nameChanging(value);
                ReportPropertyChanging("taxpayer_name");
                _taxpayer_name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("taxpayer_name");
                Ontaxpayer_nameChanged();
            }
        }
        private global::System.String _taxpayer_name;
        partial void Ontaxpayer_nameChanging(global::System.String value);
        partial void Ontaxpayer_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> taxpayer_type_id
        {
            get
            {
                return _taxpayer_type_id;
            }
            set
            {
                Ontaxpayer_type_idChanging(value);
                ReportPropertyChanging("taxpayer_type_id");
                _taxpayer_type_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("taxpayer_type_id");
                Ontaxpayer_type_idChanged();
            }
        }
        private Nullable<global::System.Int32> _taxpayer_type_id;
        partial void Ontaxpayer_type_idChanging(Nullable<global::System.Int32> value);
        partial void Ontaxpayer_type_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> taxpayer_group_id
        {
            get
            {
                return _taxpayer_group_id;
            }
            set
            {
                Ontaxpayer_group_idChanging(value);
                ReportPropertyChanging("taxpayer_group_id");
                _taxpayer_group_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("taxpayer_group_id");
                Ontaxpayer_group_idChanged();
            }
        }
        private Nullable<global::System.Int32> _taxpayer_group_id;
        partial void Ontaxpayer_group_idChanging(Nullable<global::System.Int32> value);
        partial void Ontaxpayer_group_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String taxpayer_project
        {
            get
            {
                return _taxpayer_project;
            }
            set
            {
                Ontaxpayer_projectChanging(value);
                ReportPropertyChanging("taxpayer_project");
                _taxpayer_project = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("taxpayer_project");
                Ontaxpayer_projectChanged();
            }
        }
        private global::System.String _taxpayer_project;
        partial void Ontaxpayer_projectChanging(global::System.String value);
        partial void Ontaxpayer_projectChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> taxpayer_project_finish
        {
            get
            {
                return _taxpayer_project_finish;
            }
            set
            {
                Ontaxpayer_project_finishChanging(value);
                ReportPropertyChanging("taxpayer_project_finish");
                _taxpayer_project_finish = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("taxpayer_project_finish");
                Ontaxpayer_project_finishChanged();
            }
        }
        private Nullable<global::System.Boolean> _taxpayer_project_finish;
        partial void Ontaxpayer_project_finishChanging(Nullable<global::System.Boolean> value);
        partial void Ontaxpayer_project_finishChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String taxpayer_res1
        {
            get
            {
                return _taxpayer_res1;
            }
            set
            {
                Ontaxpayer_res1Changing(value);
                ReportPropertyChanging("taxpayer_res1");
                _taxpayer_res1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("taxpayer_res1");
                Ontaxpayer_res1Changed();
            }
        }
        private global::System.String _taxpayer_res1;
        partial void Ontaxpayer_res1Changing(global::System.String value);
        partial void Ontaxpayer_res1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String taxpayer_res2
        {
            get
            {
                return _taxpayer_res2;
            }
            set
            {
                Ontaxpayer_res2Changing(value);
                ReportPropertyChanging("taxpayer_res2");
                _taxpayer_res2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("taxpayer_res2");
                Ontaxpayer_res2Changed();
            }
        }
        private global::System.String _taxpayer_res2;
        partial void Ontaxpayer_res2Changing(global::System.String value);
        partial void Ontaxpayer_res2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String taxpayer_res3
        {
            get
            {
                return _taxpayer_res3;
            }
            set
            {
                Ontaxpayer_res3Changing(value);
                ReportPropertyChanging("taxpayer_res3");
                _taxpayer_res3 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("taxpayer_res3");
                Ontaxpayer_res3Changed();
            }
        }
        private global::System.String _taxpayer_res3;
        partial void Ontaxpayer_res3Changing(global::System.String value);
        partial void Ontaxpayer_res3Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String taxpayer_res4
        {
            get
            {
                return _taxpayer_res4;
            }
            set
            {
                Ontaxpayer_res4Changing(value);
                ReportPropertyChanging("taxpayer_res4");
                _taxpayer_res4 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("taxpayer_res4");
                Ontaxpayer_res4Changed();
            }
        }
        private global::System.String _taxpayer_res4;
        partial void Ontaxpayer_res4Changing(global::System.String value);
        partial void Ontaxpayer_res4Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String taxpayer_regyear
        {
            get
            {
                return _taxpayer_regyear;
            }
            set
            {
                Ontaxpayer_regyearChanging(value);
                ReportPropertyChanging("taxpayer_regyear");
                _taxpayer_regyear = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("taxpayer_regyear");
                Ontaxpayer_regyearChanged();
            }
        }
        private global::System.String _taxpayer_regyear;
        partial void Ontaxpayer_regyearChanging(global::System.String value);
        partial void Ontaxpayer_regyearChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> taxpayer_isfree
        {
            get
            {
                return _taxpayer_isfree;
            }
            set
            {
                Ontaxpayer_isfreeChanging(value);
                ReportPropertyChanging("taxpayer_isfree");
                _taxpayer_isfree = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("taxpayer_isfree");
                Ontaxpayer_isfreeChanged();
            }
        }
        private Nullable<global::System.Boolean> _taxpayer_isfree;
        partial void Ontaxpayer_isfreeChanging(Nullable<global::System.Boolean> value);
        partial void Ontaxpayer_isfreeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> taxpayer_ftk
        {
            get
            {
                return _taxpayer_ftk;
            }
            set
            {
                Ontaxpayer_ftkChanging(value);
                ReportPropertyChanging("taxpayer_ftk");
                _taxpayer_ftk = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("taxpayer_ftk");
                Ontaxpayer_ftkChanged();
            }
        }
        private Nullable<global::System.Boolean> _taxpayer_ftk;
        partial void Ontaxpayer_ftkChanging(Nullable<global::System.Boolean> value);
        partial void Ontaxpayer_ftkChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="documentmanagerModel", Name="taxpayerdocument")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class taxpayerdocument : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new taxpayerdocument object.
        /// </summary>
        /// <param name="taxpayer_document_id">Initial value of the taxpayer_document_id property.</param>
        public static taxpayerdocument Createtaxpayerdocument(global::System.Int32 taxpayer_document_id)
        {
            taxpayerdocument taxpayerdocument = new taxpayerdocument();
            taxpayerdocument.taxpayer_document_id = taxpayer_document_id;
            return taxpayerdocument;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 taxpayer_document_id
        {
            get
            {
                return _taxpayer_document_id;
            }
            set
            {
                if (_taxpayer_document_id != value)
                {
                    Ontaxpayer_document_idChanging(value);
                    ReportPropertyChanging("taxpayer_document_id");
                    _taxpayer_document_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("taxpayer_document_id");
                    Ontaxpayer_document_idChanged();
                }
            }
        }
        private global::System.Int32 _taxpayer_document_id;
        partial void Ontaxpayer_document_idChanging(global::System.Int32 value);
        partial void Ontaxpayer_document_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> taxpayer_id
        {
            get
            {
                return _taxpayer_id;
            }
            set
            {
                Ontaxpayer_idChanging(value);
                ReportPropertyChanging("taxpayer_id");
                _taxpayer_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("taxpayer_id");
                Ontaxpayer_idChanged();
            }
        }
        private Nullable<global::System.Int32> _taxpayer_id;
        partial void Ontaxpayer_idChanging(Nullable<global::System.Int32> value);
        partial void Ontaxpayer_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String taxpayer_document_name
        {
            get
            {
                return _taxpayer_document_name;
            }
            set
            {
                Ontaxpayer_document_nameChanging(value);
                ReportPropertyChanging("taxpayer_document_name");
                _taxpayer_document_name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("taxpayer_document_name");
                Ontaxpayer_document_nameChanged();
            }
        }
        private global::System.String _taxpayer_document_name;
        partial void Ontaxpayer_document_nameChanging(global::System.String value);
        partial void Ontaxpayer_document_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> taxpayer_document_type_id
        {
            get
            {
                return _taxpayer_document_type_id;
            }
            set
            {
                Ontaxpayer_document_type_idChanging(value);
                ReportPropertyChanging("taxpayer_document_type_id");
                _taxpayer_document_type_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("taxpayer_document_type_id");
                Ontaxpayer_document_type_idChanged();
            }
        }
        private Nullable<global::System.Int32> _taxpayer_document_type_id;
        partial void Ontaxpayer_document_type_idChanging(Nullable<global::System.Int32> value);
        partial void Ontaxpayer_document_type_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String taxpayer_document_descript
        {
            get
            {
                return _taxpayer_document_descript;
            }
            set
            {
                Ontaxpayer_document_descriptChanging(value);
                ReportPropertyChanging("taxpayer_document_descript");
                _taxpayer_document_descript = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("taxpayer_document_descript");
                Ontaxpayer_document_descriptChanged();
            }
        }
        private global::System.String _taxpayer_document_descript;
        partial void Ontaxpayer_document_descriptChanging(global::System.String value);
        partial void Ontaxpayer_document_descriptChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> taxpayer_update_user_id
        {
            get
            {
                return _taxpayer_update_user_id;
            }
            set
            {
                Ontaxpayer_update_user_idChanging(value);
                ReportPropertyChanging("taxpayer_update_user_id");
                _taxpayer_update_user_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("taxpayer_update_user_id");
                Ontaxpayer_update_user_idChanged();
            }
        }
        private Nullable<global::System.Int32> _taxpayer_update_user_id;
        partial void Ontaxpayer_update_user_idChanging(Nullable<global::System.Int32> value);
        partial void Ontaxpayer_update_user_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> taxpayer_update_time
        {
            get
            {
                return _taxpayer_update_time;
            }
            set
            {
                Ontaxpayer_update_timeChanging(value);
                ReportPropertyChanging("taxpayer_update_time");
                _taxpayer_update_time = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("taxpayer_update_time");
                Ontaxpayer_update_timeChanged();
            }
        }
        private Nullable<global::System.DateTime> _taxpayer_update_time;
        partial void Ontaxpayer_update_timeChanging(Nullable<global::System.DateTime> value);
        partial void Ontaxpayer_update_timeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> taxpayer_document_bytes
        {
            get
            {
                return _taxpayer_document_bytes;
            }
            set
            {
                Ontaxpayer_document_bytesChanging(value);
                ReportPropertyChanging("taxpayer_document_bytes");
                _taxpayer_document_bytes = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("taxpayer_document_bytes");
                Ontaxpayer_document_bytesChanged();
            }
        }
        private Nullable<global::System.Int64> _taxpayer_document_bytes;
        partial void Ontaxpayer_document_bytesChanging(Nullable<global::System.Int64> value);
        partial void Ontaxpayer_document_bytesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String taxpayer_document_res1
        {
            get
            {
                return _taxpayer_document_res1;
            }
            set
            {
                Ontaxpayer_document_res1Changing(value);
                ReportPropertyChanging("taxpayer_document_res1");
                _taxpayer_document_res1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("taxpayer_document_res1");
                Ontaxpayer_document_res1Changed();
            }
        }
        private global::System.String _taxpayer_document_res1;
        partial void Ontaxpayer_document_res1Changing(global::System.String value);
        partial void Ontaxpayer_document_res1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String taxpayer_document_res2
        {
            get
            {
                return _taxpayer_document_res2;
            }
            set
            {
                Ontaxpayer_document_res2Changing(value);
                ReportPropertyChanging("taxpayer_document_res2");
                _taxpayer_document_res2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("taxpayer_document_res2");
                Ontaxpayer_document_res2Changed();
            }
        }
        private global::System.String _taxpayer_document_res2;
        partial void Ontaxpayer_document_res2Changing(global::System.String value);
        partial void Ontaxpayer_document_res2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String taxpayer_document_res3
        {
            get
            {
                return _taxpayer_document_res3;
            }
            set
            {
                Ontaxpayer_document_res3Changing(value);
                ReportPropertyChanging("taxpayer_document_res3");
                _taxpayer_document_res3 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("taxpayer_document_res3");
                Ontaxpayer_document_res3Changed();
            }
        }
        private global::System.String _taxpayer_document_res3;
        partial void Ontaxpayer_document_res3Changing(global::System.String value);
        partial void Ontaxpayer_document_res3Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String taxpayer_document_res4
        {
            get
            {
                return _taxpayer_document_res4;
            }
            set
            {
                Ontaxpayer_document_res4Changing(value);
                ReportPropertyChanging("taxpayer_document_res4");
                _taxpayer_document_res4 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("taxpayer_document_res4");
                Ontaxpayer_document_res4Changed();
            }
        }
        private global::System.String _taxpayer_document_res4;
        partial void Ontaxpayer_document_res4Changing(global::System.String value);
        partial void Ontaxpayer_document_res4Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> taxpayer_islink
        {
            get
            {
                return _taxpayer_islink;
            }
            set
            {
                Ontaxpayer_islinkChanging(value);
                ReportPropertyChanging("taxpayer_islink");
                _taxpayer_islink = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("taxpayer_islink");
                Ontaxpayer_islinkChanged();
            }
        }
        private Nullable<global::System.Boolean> _taxpayer_islink;
        partial void Ontaxpayer_islinkChanging(Nullable<global::System.Boolean> value);
        partial void Ontaxpayer_islinkChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> taxpayer_linkid
        {
            get
            {
                return _taxpayer_linkid;
            }
            set
            {
                Ontaxpayer_linkidChanging(value);
                ReportPropertyChanging("taxpayer_linkid");
                _taxpayer_linkid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("taxpayer_linkid");
                Ontaxpayer_linkidChanged();
            }
        }
        private Nullable<global::System.Int32> _taxpayer_linkid;
        partial void Ontaxpayer_linkidChanging(Nullable<global::System.Int32> value);
        partial void Ontaxpayer_linkidChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="documentmanagerModel", Name="taxpayertype")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class taxpayertype : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new taxpayertype object.
        /// </summary>
        /// <param name="taxpayertype_id">Initial value of the taxpayertype_id property.</param>
        public static taxpayertype Createtaxpayertype(global::System.Int32 taxpayertype_id)
        {
            taxpayertype taxpayertype = new taxpayertype();
            taxpayertype.taxpayertype_id = taxpayertype_id;
            return taxpayertype;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 taxpayertype_id
        {
            get
            {
                return _taxpayertype_id;
            }
            set
            {
                if (_taxpayertype_id != value)
                {
                    Ontaxpayertype_idChanging(value);
                    ReportPropertyChanging("taxpayertype_id");
                    _taxpayertype_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("taxpayertype_id");
                    Ontaxpayertype_idChanged();
                }
            }
        }
        private global::System.Int32 _taxpayertype_id;
        partial void Ontaxpayertype_idChanging(global::System.Int32 value);
        partial void Ontaxpayertype_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String taxpayertype_name
        {
            get
            {
                return _taxpayertype_name;
            }
            set
            {
                Ontaxpayertype_nameChanging(value);
                ReportPropertyChanging("taxpayertype_name");
                _taxpayertype_name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("taxpayertype_name");
                Ontaxpayertype_nameChanged();
            }
        }
        private global::System.String _taxpayertype_name;
        partial void Ontaxpayertype_nameChanging(global::System.String value);
        partial void Ontaxpayertype_nameChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="documentmanagerModel", Name="user")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class user : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new user object.
        /// </summary>
        /// <param name="user_id">Initial value of the user_id property.</param>
        public static user Createuser(global::System.Int32 user_id)
        {
            user user = new user();
            user.user_id = user_id;
            return user;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 user_id
        {
            get
            {
                return _user_id;
            }
            set
            {
                if (_user_id != value)
                {
                    Onuser_idChanging(value);
                    ReportPropertyChanging("user_id");
                    _user_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("user_id");
                    Onuser_idChanged();
                }
            }
        }
        private global::System.Int32 _user_id;
        partial void Onuser_idChanging(global::System.Int32 value);
        partial void Onuser_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String user_name
        {
            get
            {
                return _user_name;
            }
            set
            {
                Onuser_nameChanging(value);
                ReportPropertyChanging("user_name");
                _user_name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("user_name");
                Onuser_nameChanged();
            }
        }
        private global::System.String _user_name;
        partial void Onuser_nameChanging(global::System.String value);
        partial void Onuser_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String user_password
        {
            get
            {
                return _user_password;
            }
            set
            {
                Onuser_passwordChanging(value);
                ReportPropertyChanging("user_password");
                _user_password = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("user_password");
                Onuser_passwordChanged();
            }
        }
        private global::System.String _user_password;
        partial void Onuser_passwordChanging(global::System.String value);
        partial void Onuser_passwordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String user_cname
        {
            get
            {
                return _user_cname;
            }
            set
            {
                Onuser_cnameChanging(value);
                ReportPropertyChanging("user_cname");
                _user_cname = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("user_cname");
                Onuser_cnameChanged();
            }
        }
        private global::System.String _user_cname;
        partial void Onuser_cnameChanging(global::System.String value);
        partial void Onuser_cnameChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="documentmanagerModel", Name="useraction")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class useraction : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new useraction object.
        /// </summary>
        /// <param name="user_action_id">Initial value of the user_action_id property.</param>
        public static useraction Createuseraction(global::System.Int32 user_action_id)
        {
            useraction useraction = new useraction();
            useraction.user_action_id = user_action_id;
            return useraction;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 user_action_id
        {
            get
            {
                return _user_action_id;
            }
            set
            {
                if (_user_action_id != value)
                {
                    Onuser_action_idChanging(value);
                    ReportPropertyChanging("user_action_id");
                    _user_action_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("user_action_id");
                    Onuser_action_idChanged();
                }
            }
        }
        private global::System.Int32 _user_action_id;
        partial void Onuser_action_idChanging(global::System.Int32 value);
        partial void Onuser_action_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> user_id
        {
            get
            {
                return _user_id;
            }
            set
            {
                Onuser_idChanging(value);
                ReportPropertyChanging("user_id");
                _user_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("user_id");
                Onuser_idChanged();
            }
        }
        private Nullable<global::System.Int32> _user_id;
        partial void Onuser_idChanging(Nullable<global::System.Int32> value);
        partial void Onuser_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> action_id
        {
            get
            {
                return _action_id;
            }
            set
            {
                Onaction_idChanging(value);
                ReportPropertyChanging("action_id");
                _action_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("action_id");
                Onaction_idChanged();
            }
        }
        private Nullable<global::System.Int32> _action_id;
        partial void Onaction_idChanging(Nullable<global::System.Int32> value);
        partial void Onaction_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> hasRight
        {
            get
            {
                return _hasRight;
            }
            set
            {
                OnhasRightChanging(value);
                ReportPropertyChanging("hasRight");
                _hasRight = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("hasRight");
                OnhasRightChanged();
            }
        }
        private Nullable<global::System.Boolean> _hasRight;
        partial void OnhasRightChanging(Nullable<global::System.Boolean> value);
        partial void OnhasRightChanged();

        #endregion

    
    }

    #endregion

    
}
